# ============================================
# Render Blueprint for AdonisJS + Inertia
# Deploy with: render.yaml in root directory
# ============================================

services:
  # ============================================
  # Web Service (Node.js)
  # ============================================
  - type: web
    name: g-agency-events
    runtime: node
    region: frankfurt  # or: oregon, frankfurt, singapore
    plan: free
    branch: main
    
    # Build & Start commands
    buildCommand: npm run render:build
    startCommand: npm run render:start
    
    # Environment variables
    envVars:
      - key: NODE_ENV
        value: production
      
      - key: PORT
        value: 10000
      
      - key: HOST
        value: 0.0.0.0
      
      - key: APP_KEY
        generateValue: true
        sync: false
      
      - key: APP_URL
        value: https://g-agency-events.onrender.com
      
      - key: LOG_LEVEL
        value: info
      
      # Session
      - key: SESSION_DRIVER
        value: cookie
      
      # Database - Configure manually in Render dashboard
      - key: DB_HOST
        sync: false
      
      - key: DB_PORT
        value: 3306
      
      - key: DB_USER
        sync: false
      
      - key: DB_PASSWORD
        sync: false
      
      - key: DB_DATABASE
        sync: false
      
      # Email
      - key: SMTP_HOST
        sync: false
      
      - key: SMTP_PORT
        value: 587
      
      - key: SMTP_USERNAME
        sync: false
      
      - key: SMTP_PASSWORD
        sync: false
      
      - key: MAIL_FROM_ADDRESS
        sync: false
      
      - key: MAIL_FROM_NAME
        value: G-Agency Events
      
      - key: MAIL_REPLY_TO_ADDRESS
        sync: false
      
      - key: MAIL_REPLY_TO_NAME
        value: Support Team
      
      # Storage
      - key: DRIVE_DISK
        value: fs
      
      # Admin Token
      - key: ADMIN_API_TOKEN
        generateValue: true
        sync: false
      
      - key: ADMIN_TOKEN_EXPIRES_IN
        value: 720
      
      # Typesense (Disable for free tier)
      - key: TYPESENSE_ENABLED
        value: false
      
      - key: TYPESENSE_HOST
        value: localhost
      
      - key: TYPESENSE_PORT
        value: 8108
      
      - key: TYPESENSE_PROTOCOL
        value: http
      
      - key: TYPESENSE_API_KEY
        sync: false
    
    # Health check
    healthCheckPath: /
    
    # Persistent disk for uploads (optional - paid feature)
    # disk:
    #   name: uploads
    #   mountPath: /app/public/uploads
    #   sizeGB: 1

# ============================================
# Optional: Database (if not using external)
# ============================================
# databases:
#   - name: events-db
#     plan: free
#     databaseName: events_platform
#     user: g_agency